version: '3.4'

services:
  chirper:
    volumes:
      - ./app:/chirper
    ports:
      - 3000:3000
    tty: true
    container_name: 'tweets'
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
